# Generated by Django 3.2.8 on 2021-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_title', models.CharField(max_length=30, verbose_name='شرح هزینه')),
                ('cost_type', models.CharField(max_length=100, verbose_name='نوع هزینه')),
                ('cost_date', models.DateField(verbose_name='تاریخ ')),
                ('cost_amount', models.IntegerField(verbose_name='مبلغ هزینه')),
                ('cost_description', models.TextField(max_length=300, verbose_name='توضیحات هزینه')),
            ],
        ),
    ]
